### ISSUE TITLE
compile errors in docker env

### ISSUE THREAD

**Issue by QiMingZhenFan** [shuttworth/MarkDownBlogPicture#1]
Hi, thanks for your contributions!

I get compile errors in the docker env which you provided here: https://github.com/electech6/LVI-SAM_detailed_comments#%E4%BA%8Cdocker%E7%8E%AF%E5%A2%83%E9%93%BE%E6%8E%A5

The [original lvi-sam code](https://github.com/TixiaoShan/LVI-SAM) can be successfully built by catkin_make in this docker env, but [LVI-SAM_detailed_comments](https://github.com/electech6/LVI-SAM_detailed_comments) cannot pass.

![FHkaib8WU7](https://user-images.githubusercontent.com/38323127/175469951-98148904-8a56-4e05-a83c-9df3f5a4cba1.png)

**Comment by shuttworth** [comment]
Thanks for your timely testing and feedback!
We have fixed the error and updated the annotated version of the code, so you can pull up the latest code into dcoker image to compile!
![image](https://user-images.githubusercontent.com/46838923/175856452-620067e7-715e-4c75-9976-6b2c4c7c38ff.png)
